library(MVN)
library(car)
library(heplots)


whisky <- read.table("2024_06_13/whisky.txt", h=TRUE)

# a) Do you believe the rows of the data matrix have been independently
# generated by the same tri-variate Gaussian
# distribution? Justify your answer.

mvn(whisky) 
# As we seen from MVN test, our data MVN,
# $multivariateNormality
# Test        HZ   p value MVN
# 1 Henze-Zirkler 0.6264444 0.1615312 YES 
#
# $univariateNormality
# Test  Variable Statistic   p value Normality
# 1 Anderson-Darling    t1        1.2547    0.0015    NO    
# 2 Anderson-Darling    t2        1.3871    0.0006    NO    
# 3 Anderson-Darling    t3        1.1552    0.0027    NO    
#
# $Descriptives
# n Mean  Std.Dev Median Min Max  25th  75th     Skew   Kurtosis
# t1 10   77 78.14516   40.0  20 235 31.25 78.75 1.127795 -0.5195660
# t2 10   76 75.30678   42.5  20 225 30.00 73.75 1.147665 -0.5253891
# t3 10   69 76.07745   37.5   5 215 20.00 73.75 1.062872 -0.6564829

# But problem with normality on each group...
shapiro.test(whisky$t1)
shapiro.test(whisky$t2)
shapiro.test(whisky$t3)

# b) Do you think that one of the tasters tends to over/under-price the bottles compared to the two others? After
# having verified any required assumptions, support your answer with a 95% level test.

boxplot(whisky)
data_difference <- data.frame(
  t12 = whisky$t1 - whisky$t2,
  t13 = whisky$t1 - whisky$t3
)

boxplot(data_difference) 
plot(data_difference)
mvn(data_difference) # differences 

mu0      <- c(0, 0) # H0, that difference is zero
x.mean   <- colMeans(data_difference)
x.cov    <- cov(data_difference)
x.invcov <- solve(x.cov)
n <- 10 # each group has 10 observations
p <- 2 # check two means on zero

x.T2 <- n * (x.mean-mu0) %*% x.invcov %*% (x.mean-mu0) 
Pb <- 1-pf(x.T2*(n-p)/(p*(n-1)), p, n-p)
Pb # 0.006252078 < 0.05, so we can reject, that mean difference = 0

# c) Provide a plot of the confidence region for the mean vector of the differences in price evaluation between t1 and
# each of the two other tasters.

# mean under H0 (blue)
points(mu0[1], mu0[2], col='blue', pch=16)

# sample mean (black)
points(x.mean[1], x.mean[2], col='black', pch=16)

# we represent the confidence region of level 95%: where does mu0 fall?
alpha <- .05
cfr.fisher <- (p*(n-1)/(n-p))*qf(1-alpha,p,n-p)
ellipse(center=x.mean, shape=x.cov/n, radius=sqrt(cfr.fisher), lwd=2)
# as we see, CI doesn't contain 0, so we can reject H0 of zero mean

# d) Provide two Bonferroni simultaneous confidence intervals of global level 95% for the mean of the di↵erence in
# price evaluation between t1 and each of the two other tasters.

k <- 2 # if we also wanted to plot for variances => k = 4
alpha <- 0.05


ICmean <- cbind(inf=x.mean - sqrt(diag(x.cov)/n) * qt(1 - alpha/(2*k), n-1),
                center= x.mean,
                sup= x.mean + sqrt(diag(x.cov)/n) * qt(1 - alpha/(2*k), n-1))

# ICvar <- cbind(inf=diag(x.cov)*(n-1) / qchisq(1 - alpha/(2*k), n-1),
#                center=diag(x.cov),
#                sup=diag(x.cov)*(n-1) / qchisq(alpha/(2*k), n-1))

ICmean
#          inf    center   sup
# t12 -3.819742      1  5.819742
# t13  2.269181      8 13.730819

# So for difference among 1 and 2 we can not say, that there are any difference
# But for 1 and 3 there is difference among mean values 

ICvar

# trial with ANOVA, but don't think that it's correct one ----------------------
# b) Do you think that one of the tasters tends to over/under-price the bottles compared to the two others? After
# having verified any required assumptions, support your answer with a 95% level test.
whisky_anova_data <- data.frame(
  value=c(whisky$t1, whisky$t2, whisky$t3),
  taster=c(rep("t1", 10), rep("t2", 10), rep("t3", 10))
)

fit <- aov(value ~ taster, data=whisky_anova_data)
summary(fit)
#             Df Sum Sq Mean Sq F value Pr(>F)
# taster       2    380     190   0.032  0.968
# Residuals   27 158090    5855
# p-value > 0.05, so we can not reject H0 of equal means 

# Check assumptions
bartlett.test(whisky_anova_data$value, whisky_anova_data$taster)
# p-value = 0.9937 => can not reject H0 of equal variances among groups

# c) Provide a plot of the confidence region for the mean vector of the differences in price evaluation between t1 and
# each of the two other tasters.



